#===============================================================================
# Makefile.validate : POPScomp pipeline for FunPDBe 
# This script is invoked for each PDBML subdirectory by the master Makefile.
# POPSed PDBML files (i.e. *.json files in the 'JSON/' output database)
# are validated using a python script.
# Only non-zero size files are checked and those that pass are linked. 
# If the validation fails, the target (link) is removed.
# This mechanism ensures that updated JSON files that fail are not kept linked
# because an older version of that file has passed and therefore a link exists.
#
# Copyright (C) 2019-2020 Jens Kleinjung
#===============================================================================

#_______________________________________________________________________________
## macros
JSONFILES := $(shell find ${JSONDIR}/$X -name '*.json' -size '+0c' -printf "%f\n")

#_______________________________________________________________________________
## suffix rules
.SUFFIXES :

.SUFFIXES : .json

%.json :
	(${FUNPDBEDIR}/funpdbe-client/funpdbe_client.py --path=${JSONDIR}/$X/$@ --mode=validate 2>&1 | grep -q complies && ln -s ${JSONDIR}/$X/$@) || rm -f $@

#_______________________________________________________________________________
## targets

.PHONY : validate

validate : ${JSONFILES}

#===============================================================================

