#===============================================================================
# Makefile.subdir : POPScomp pipeline for FunPDBe 
# This is invoked for each subdirectory by the master Makefile.
# Existing *.xml.gz structure files are POPSed if their JSON output file,
#   here implied as dependency of 'all' target, needs updating.
# Copyright (C) 2019 Jens Kleinjung
#===============================================================================

#_______________________________________________________________________________
## macros
## creates .json dependencies from list of *.xml.gz
#JSONFILES := $(patsubst %.xml.gz,%.json,$(wildcard *.xml.gz))
## creates .json dependencies from list of *.xml.gz using upper file size limit
JSONFILES := $(patsubst %.xml.gz,%.json,$(shell find ./ -name '*.xml.gz' -size 1M))

#_______________________________________________________________________________
## suffix rules
.SUFFIXES :

.SUFFIXES : .json

%.json : %.xml.gz
	-@ touch $@
	-@${POPSC} --pdbml $^ ${POPSFLAGS}

#_______________________________________________________________________________
## targets
all : ${JSONFILES} 

#===============================================================================

