#===============================================================================
# Makefile.subdir : POPScomp pipeline for FunPDBe 
# This is invoked for each subdirectory by the master Makefile.
# Existing *.xml.gz structure files are POPSed if their JSON output file,
#   here implied as dependency of 'all' target, needs updating.
# Copyright (C) 2019 Jens Kleinjung
#===============================================================================

#_______________________________________________________________________________
## macros
## creates .json dependencies from list of *.xml.gz
#JSONFILES := $(patsubst %.xml.gz,%.json,$(wildcard *.xml.gz))
## creates .json dependencies from list of *.xml.gz using upper file size limit
## the printf command is needed to remove the path of the target file name,
##   because file size comes from 'XML/', but output goes to 'JSON/'
##  -500k :  5-20 s
## -1000k : 0.5-2 min
## -2000k : 2-8 min
## -4000k : 8-30 min

JSONFILES := $(patsubst %.xml.gz,%.json,$(shell find ${PDBDIR}/$X -name '*.xml.gz' -size '-4000k' -printf "%f\n"))

#_______________________________________________________________________________
## suffix rules
.SUFFIXES :

.SUFFIXES : .json

%.json : %.xml.gz
	-@ touch $@
	-@${POPSC} --pdbml $^ ${POPSFLAGS}

#_______________________________________________________________________________
## targets
all : ${JSONFILES} 

#===============================================================================

