name: R CI

on: [push]

jobs:
  R-CMD-CHECK:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.3'
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("knitr"), dependencies = TRUE)'
      - name: compile POPSR
        run: R CMD build POPSR
